name: Test and run Prettier
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Test, Prettier and Build
        run: |
          npm ci
          npm run unit-tests
          npm run integration-tests
          npm run prettier
          npm run build

